config/routes.rb
BasicStarterTemplate::Application.routes.draw do
  get "admin" => "admin#index"
  resources :jobs

  resources :contact_infos

  devise_for :users
  root 'home#index'
end

app/models/contact_info.rb
class ContactInfo < ActiveRecord::Base
end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  	@contact_info = ContactInfo.first
  	@jobs = Job.all 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/contact_infos_controller.rb
class ContactInfosController < ApplicationController
  before_action :set_contact_info, only: [:show, :edit, :update, :destroy]

  # GET /contact_infos
  # GET /contact_infos.json
  def index
    @contact_infos = ContactInfo.all
  end

  # GET /contact_infos/1
  # GET /contact_infos/1.json
  def show
  end

  # GET /contact_infos/new
  def new
    @contact_info = ContactInfo.new
  end

  # GET /contact_infos/1/edit
  def edit
  end

  # POST /contact_infos
  # POST /contact_infos.json
  def create
    @contact_info = ContactInfo.new(contact_info_params)

    respond_to do |format|
      if @contact_info.save
        format.html { redirect_to @contact_info, notice: 'Contact info was successfully created.' }
        format.json { render action: 'show', status: :created, location: @contact_info }
      else
        format.html { render action: 'new' }
        format.json { render json: @contact_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contact_infos/1
  # PATCH/PUT /contact_infos/1.json
  def update
    respond_to do |format|
      if @contact_info.update(contact_info_params)
        format.html { redirect_to @contact_info, notice: 'Contact info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @contact_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_infos/1
  # DELETE /contact_infos/1.json
  def destroy
    @contact_info.destroy
    respond_to do |format|
      format.html { redirect_to contact_infos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact_info
      @contact_info = ContactInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_info_params
      params.require(:contact_info).permit(:first_name, :last_name, :address_1, :address_2, :suburb, :postcode, :country, :email, :phone, :linkedin, :twitter, :blog, :profile_pic)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  	@contact_info = ContactInfo.first
  	@jobs = Job.all 
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render action: 'show', status: :created, location: @job }
      else
        format.html { render action: 'new' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:company, :start_date, :end_date, :position, :summary)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_infos_helper.rb
module ContactInfosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/admin/index.html.erb
<h1>Admin Page</h1>

<div class="row">

	<div class="col-md-6">
	<h2>My contact info</h2>
		<%= render 'contact_infos/form' %>
	
	</div>

	<div class="col-md-6">
		<%= render 'jobs/index' %>
	
	</div>

</div>

app/views/contact_infos/_form.html.erb
<%= simple_form_for(@contact_info) do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <%= f.input :first_name, input_html: { class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.input :last_name, input_html: { class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.input :address_1, input_html: { class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.input :address_2, input_html: { class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.input :suburb, input_html: { class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.input :postcode, input_html: { class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.input :country, input_html: { class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.input :email, input_html: { class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.input :phone, input_html: { class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.input :linkedin, input_html: { class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.input :twitter, input_html: { class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.input :blog, input_html: { class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.input :profile_pic, input_html: { class: 'form-control'} %>
  </div>

  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/contact_infos/edit.html.erb
<h1>Editing contact_info</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact_info %> |
<%= link_to 'Back', contact_infos_path %>

app/views/contact_infos/index.html.erb
<h1>Listing contact_infos</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Address 1</th>
      <th>Address 2</th>
      <th>Suburb</th>
      <th>Postcode</th>
      <th>Country</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Linkedin</th>
      <th>Twitter</th>
      <th>Blog</th>
      <th>Profile pic</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contact_infos.each do |contact_info| %>
      <tr>
        <td><%= contact_info.first_name %></td>
        <td><%= contact_info.last_name %></td>
        <td><%= contact_info.address_1 %></td>
        <td><%= contact_info.address_2 %></td>
        <td><%= contact_info.suburb %></td>
        <td><%= contact_info.postcode %></td>
        <td><%= contact_info.country %></td>
        <td><%= contact_info.email %></td>
        <td><%= contact_info.phone %></td>
        <td><%= contact_info.linkedin %></td>
        <td><%= contact_info.twitter %></td>
        <td><%= contact_info.blog %></td>
        <td><%= contact_info.profile_pic %></td>
        <td><%= link_to 'Show', contact_info %></td>
        <td><%= link_to 'Edit', edit_contact_info_path(contact_info) %></td>
        <td><%= link_to 'Destroy', contact_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact info', new_contact_info_path %>

app/views/contact_infos/new.html.erb
<h1>New contact_info</h1>

<%= render 'form' %>

<%= link_to 'Back', contact_infos_path %>

app/views/contact_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @contact_info.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @contact_info.last_name %>
</p>

<p>
  <strong>Address 1:</strong>
  <%= @contact_info.address_1 %>
</p>

<p>
  <strong>Address 2:</strong>
  <%= @contact_info.address_2 %>
</p>

<p>
  <strong>Suburb:</strong>
  <%= @contact_info.suburb %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @contact_info.postcode %>
</p>

<p>
  <strong>Country:</strong>
  <%= @contact_info.country %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact_info.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contact_info.phone %>
</p>

<p>
  <strong>Linkedin:</strong>
  <%= @contact_info.linkedin %>
</p>

<p>
  <strong>Twitter:</strong>
  <%= @contact_info.twitter %>
</p>

<p>
  <strong>Blog:</strong>
  <%= @contact_info.blog %>
</p>

<p>
  <strong>Profile pic:</strong>
  <%= @contact_info.profile_pic %>
</p>

<%= link_to 'Edit', edit_contact_info_path(@contact_info) %> |
<%= link_to 'Back', contact_infos_path %>

app/views/home/index.html.erb
<div id="headerwrap">
		<div class="container">
			<div class="row centered">
				<div class="col-lg-12">
					<h1><%= @contact_info.first_name %> <%= @contact_info.last_name %></h1>
					<h3>Person | michael@planetearth.com</h3>
				</div><!--/.col-lg-12 -->
			</div><!--/.row -->
		</div><!--/.container -->
	</div><!--/.#headerwrap -->
	

	<section id="about" name="about"></section>
	<div id="intro">
		<div class="container">
			<div class="row">
				
				<div class="col-lg-2 col-lg-offset-1">
					<h5>ABOUT</h5>
				</div>
				<div class="col-lg-6">
					<p>I'm web designer & front-end developer with 7 years of professional experience. I'm interested in all kinds of visual communication, but my major focus is on designing web, mobile & tablet interfaces. I also have skills in other fields like branding, icon design or web development.</p>
				</div>
				<div class="col-lg-3">
					<p><a href="#"><i class="icon-file"></i></a> <sm>DOWNLOAD PDF</sm></p>
				</div>
				
			</div><!--/.row -->
		</div><!--/.container -->
	</div><!--/ #intro -->


	<section id="resume" name="resume"></section>
	<!--EDUCATION DESCRIPTION -->
	<div class="container desc">
		<div class="row">

				<div class="col-lg-2 col-lg-offset-1">
					<h5>EDUCATION</h5>
				</div>
				<div class="col-lg-6">
					<p><t>Master of Web Design</t><br/>
						St. Patrick University <br/>
						<i>3 Years Course</i>
					</p>
				</div>
				<div class="col-lg-3">
					<p><sm>GRADUATING IN MAY 2014</sm><br/>
					<imp><sm>IN PROGRESS</sm></imp>
					</p>
				</div>
	
				<div class="col-lg-6 col-lg-offset-3">
					<p><t>Degree of Web Developer</t><br/>
						Hastings University <br/>
						<i>2 Years Course</i>
					</p>
				</div>
				<div class="col-lg-3">
					<p><sm>JUNE 2012</sm></p>
				</div>
	
		</div><!--/.row -->
		<br>
		<hr>
	</div><!--/.container -->
	
	
	<!--WORK DESCRIPTION -->
	<div class="container desc">
		
		<% if @jobs %>

				<% @jobs.each_with_index do |job, index| %>

		<div class="row">

		
				<div class="col-lg-2 col-lg-offset-1">
					<% if index == 0 %><h5>WORK</h5><% end %>
				</div>
				
				
				<div class="col-lg-6">
				
					<p><t><%= job.position %></t><br/>
						<%= job.company %> <br/>
					</p>
					<p><more><%= job.summary %></more></p>
				</div>
				<div class="col-lg-3">
					<p><sm><%= job.start_date.strftime( '%B %Y') %> - <%= job.end_date.strftime( '%B %Y') %></sm></p>
				</div>



<!--
				<div class="col-lg-6 col-lg-offset-3">
					<p><t>Web Designer - Intern</t><br/>
						Onassis Ltd. <br/>
					</p>
					<p><more>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</more></p>
				</div>
				<div class="col-lg-3">
					<p><sm>JUNE 2010 - JULY 2012</sm></p>
				</div>
-->
		</div><!--/.row -->
		  <% end %>
		 <% end %>
		<br>
		<hr>
	</div><!--/.container -->


	<!--AWARDS DESCRIPTION -->
	<div class="container desc">
		<div class="row">
				<div class="col-lg-2 col-lg-offset-1">
					<h5>AWARDS</h5>
				</div>
				<div class="col-lg-6">
					<p><t>Best Web Design</t><br/>
						Black Tie Site <br/>
					</p>
				</div>
				<div class="col-lg-3">
					<p><sm>NOVEMBER 2013</sm></p>
				</div>
	
				<div class="col-lg-6 col-lg-offset-3">
					<p><t>Designer of the Year</t><br/>
						Awwwards Site
					</p>
					<p><more>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</more></p>
				</div>
				<div class="col-lg-3">
					<p><sm>2013</sm></p>
				</div>
		
		</div><!--/.row -->
		<br>
	</div><!--/.container -->
	
	
	<!--SKILLS DESCRIPTION -->
	<div id="skillswrap">
		<div class="container">
			<div class="row">
					<div class="col-lg-2 col-lg-offset-1">
						<h5>SKILLS</h5>
					</div>
					<div class="col-lg-3 centered">
						<canvas id="javascript" height="130" width="130"></canvas>
						<p>Javascript</p>
						<br>
						<script>
							var doughnutData = [
									{
										value: 70,
										color:"#1abc9c"
									},
									{
										value : 30,
										color : "#ecf0f1"
									}
								];
								var myDoughnut = new Chart(document.getElementById("javascript").getContext("2d")).Doughnut(doughnutData);
						</script>
					</div>
					<div class="col-lg-3 centered">
						<canvas id="bootstrap" height="130" width="130"></canvas>
						<p>Bootstrap</p>
						<br>
						<script>
							var doughnutData = [
									{
										value: 90,
										color:"#1abc9c"
									},
									{
										value : 10,
										color : "#ecf0f1"
									}
								];
								var myDoughnut = new Chart(document.getElementById("bootstrap").getContext("2d")).Doughnut(doughnutData);
						</script>
					</div>
					<div class="col-lg-3 centered">
						<canvas id="wordpress" height="130" width="130"></canvas>
						<p>Wordpress</p>
						<br>
						<script>
							var doughnutData = [
									{
										value: 65,
										color:"#1abc9c"
									},
									{
										value : 35,
										color : "#ecf0f1"
									}
								];
								var myDoughnut = new Chart(document.getElementById("wordpress").getContext("2d")).Doughnut(doughnutData);
						</script>
					</div>
					
					<div class="col-lg-3 col-lg-offset-3 centered">
						<canvas id="html" height="130" width="130"></canvas>
						<p>HTML/CSS</p>
						<br>
						<script>
							var doughnutData = [
									{
										value: 80,
										color:"#1abc9c"
									},
									{
										value : 20,
										color : "#ecf0f1"
									}
								];
								var myDoughnut = new Chart(document.getElementById("html").getContext("2d")).Doughnut(doughnutData);
						</script>
					</div>
					<div class="col-lg-3 centered">
						<canvas id="photoshop" height="130" width="130"></canvas>
						<p>Photoshop</p>
						<br>
						<script>
							var doughnutData = [
									{
										value: 70,
										color:"#1abc9c"
									},
									{
										value : 30,
										color : "#ecf0f1"
									}
								];
								var myDoughnut = new Chart(document.getElementById("photoshop").getContext("2d")).Doughnut(doughnutData);
						</script>
					</div>
					<div class="col-lg-3 centered">
						<canvas id="illustrator" height="130" width="130"></canvas>
						<p>Illustrator</p>
						<br>
						<script>
							var doughnutData = [
									{
										value: 50,
										color:"#1abc9c"
									},
									{
										value : 50,
										color : "#ecf0f1"
									}
								];
								var myDoughnut = new Chart(document.getElementById("illustrator").getContext("2d")).Doughnut(doughnutData);
						</script>
					</div>

			</div><!--/.row -->
			<br>
		</div><!--/.container -->
	</div><!--/ #skillswrap -->



	<section id="work" name="work"></section>
	<!--PORTFOLIO DESCRIPTION -->
	<div class="container desc">
		<div class="row">
				<div class="col-lg-2 col-lg-offset-1">
					<h5>PORTFOLIO</h5>
				</div>
				<div class="col-lg-6">
					<p><img class="img-responsive" src="assets/img/port01.jpg" alt=""></p>
				</div>
				<div class="col-lg-3">
					<p>CANALS OF ENGLAND</p>
				<p><more>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.<br/><br/>
					<sm><i class="icon-tag"></i> design</sm></more> 
				</p>
				</div>
	
				<div class="col-lg-6 col-lg-offset-3">
					<p><img class="img-responsive" src="assets/img/port02.jpg" alt=""></p>
				</div>
				<div class="col-lg-3">
						<p>SANKEY</p>
					<p><more>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.<br/><br/>
						<sm><i class="icon-tag"></i> front-end</sm></more> 
					</p>
				</div>
				
				<div class="col-lg-6 col-lg-offset-3">
					<p><img class="img-responsive" src="assets/img/port03.jpg" alt=""></p>
				</div>
				<div class="col-lg-3">
						<p>WE GROW</p>
					<p><more>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.<br/><br/>
						<sm><i class="icon-tag"></i> web design</sm></more> 
					</p>
				</div>
		
		</div><!--/.row -->
		<br>
		<br>
	</div><!--/.container -->
	


	<section id="contact" name="contact"></section>
	<!--FOOTER DESCRIPTION -->
	<div id="footwrap">
		<div class="container">
			<div class="row">
			
				<div class="col-lg-2 col-lg-offset-1">
					<h5>CONTACT</h5>
				</div>
				<div class="col-lg-6">
					<p><t>Email</t><br/>
						william@blacktie.co <br/>
					</p>
					<p><t>Adress</t><br/>
						<%= @contact_info.address_1 %> <br/>
						<%= @contact_info.address_2 %> <br/>
						<%= @contact_info.suburb %> <br/>
						<%= @contact_info.postcode %> <%= @contact_info.country %> <br/><br/>
					</p>
					<p><t>Phone</t><br/>
						+55 8933-2383 <br/>
					</p>
				</div>
				<div class="col-lg-3">
					<p><sm>SOCIAL LINKS</sm></p>
					<p>
						<a href="#"><i class="icon-dribbble"></i></a>
						<a href="#"><i class="icon-twitter"></i></a>
						<a href="#"><i class="icon-facebook"></i></a>
						<a href="#"><i class="icon-linkedin"></i></a>
						<a href="#"><i class="icon-apple"></i></a>

					</p>
				</div>
			</div><!--/.row -->
		</div><!--/.container -->
	</div><!--/ #footer -->
	
	<div id="c">
		<div class="container">
			<p>Created by <a href="http://www.blacktie.co">BLACKTIE.CO</a></p>
		
		</div>
	</div>

app/views/jobs/_form.html.erb
<%= simple_form_for(@job) do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <%= f.input :company, input_html: { class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.input :start_date, input_html: { class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.input :end_date, input_html: { class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.input :position, input_html: { class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.input :summary, input_html: { class: 'form-control'} %>
  </div>

  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/jobs/_index.html.erb
<h1>Listing jobs</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Position</th>
      <th>Summary</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.company %></td>
        <td><%= job.start_date %></td>
        <td><%= job.end_date %></td>
        <td><%= job.position %></td>
        <td><%= job.summary %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @job.company %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @job.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @job.end_date %>
</p>

<p>
  <strong>Position:</strong>
  <%= @job.position %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @job.summary %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default navbar-fixed-bottom" role="navigation">
  <div class="container">
  <a class="navbar-brand pull-right" href="https://thecoderfactory.com">The Coder Factory</a>
  </div>
</nav>

app/views/layouts/_navigation.html.erb
<div id="section-topbar">
    <div id="topbar-inner">
      <div class="container">
        <div class="row">
          <div class="dropdown">
            <ul id="nav" class="nav">
              <li class="menu-item"><a class="smoothScroll" href="#about" title="About"><i class="fa fa-user"></i></a></li>
              <li class="menu-item"><a class="smoothScroll" href="#resume" title="Resume"><i class="fa fa-file"></i></a></li>
              <li class="menu-item"><a class="smoothScroll" href="#work" title="Works"><i class="fa fa-briefcase"></i></a></li>
              <li class="menu-item"><a class="smoothScroll" href="#contact" title="Contact"><i class="fa fa-envelope"></i></a></li>

              <% if user_signed_in? %>
              <li class="menu-item"><a href="<%= root_path %>" title="Home"><i class="fa fa-home"></i></a></li>
              <li class="menu-item"><a href="<%= admin_path %>" title="Home"><i class="fa fa-cogs"></i></a></li>
              <% end %>

            </ul><!--/ uL#nav -->
          </div><!-- /.dropdown -->

          <div class="clear"></div>
        </div><!--/.row -->
      </div><!--/.container -->

      <div class="clear"></div>
    </div><!--/ #topbar-inner -->
  </div><!--/ #section-topbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : "The Coder Factory" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "The Coder Factory" %>">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,700' rel='stylesheet' type='text/css'>
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
</head>
<body data-spy="scroll" data-offset="0" data-target="#nav">
	<%= render 'layouts/navigation' %>
	
		<%= yield %>

  <%= render 'layouts/footer' %>
</body>
</html>